INSERT INTO titles (name, year, genre, synopsis, poster, trending_rank)
SELECT * FROM (VALUES
  ('Stranger Things', 2016, 'Trending', 'Kids in Hawkins uncover a secret lab and a parallel dimension.', '/img/posters/stranger-things.jpg', 1),
  ('Wednesday', 2022, 'Trending', 'Wednesday Addams navigates Nevermore Academy.', '/img/posters/wednesday.jpg', 2),
  ('Money Heist', 2017, 'Trending', 'A criminal mastermind plans the biggest heist in history.', '/img/posters/money-heist.jpg', 3),
  ('The Witcher', 2019, 'Trending', 'Geralt of Rivia, a monster hunter, finds his destiny.', '/img/posters/the-witcher.jpg', 4),
  ('Squid Game', 2021, 'Trending', 'Players risk their lives in deadly childrens games for cash.', '/img/posters/squid-game.jpg', 5),
  ('Dark', 2017, 'Trending', 'Four families and a time-travel conspiracy in a German town.', '/img/posters/dark.jpg', 6),
  ('The Crown', 2016, 'Trending', 'The reign of Queen Elizabeth II across decades.', '/img/posters/the-crown.jpg', 7),
  ('Bridgerton', 2020, 'Trending', 'Regency-era London romance and scandal.', '/img/posters/bridgerton.jpg', 8),
  ('Lupin', 2021, 'Trending', 'A gentleman thief inspired by Arsene Lupin seeks revenge.', '/img/posters/lupin.jpg', 9),
  ('Narcos', 2015, 'Trending', 'The rise and fall of the Medellin drug cartel.', '/img/posters/narcos.jpg', 10),
  ('Breaking Bad', 2008, 'Drama', 'A chemistry teacher turns to making meth.', '/img/posters/breaking-bad.jpg', NULL),
  ('The Queens Gambit', 2020, 'Drama', 'An orphan becomes a chess prodigy.', '/img/posters/queens-gambit.jpg', NULL),
  ('Ozark', 2017, 'Drama', 'A financial planner launders money for a cartel.', '/img/posters/ozark.jpg', NULL),
  ('Peaky Blinders', 2013, 'Drama', 'A gangster family in post-war Birmingham.', '/img/posters/peaky-blinders.jpg', NULL),
  ('When They See Us', 2019, 'Drama', 'Five teens wrongly accused in the Central Park case.', '/img/posters/when-they-see-us.jpg', NULL),
  ('Unbelievable', 2019, 'Drama', 'Detectives track a serial rapist across states.', '/img/posters/unbelievable.jpg', NULL),
  ('The Umbrella Academy', 2019, 'Action', 'Dysfunctional sibling superheroes stop the apocalypse.', '/img/posters/umbrella-academy.jpg', NULL),
  ('Extraction', 2020, 'Action', 'A mercenary rescues a crime lords kidnapped son.', '/img/posters/extraction.jpg', NULL),
  ('The Old Guard', 2020, 'Action', 'Immortal mercenaries protect their secret.', '/img/posters/old-guard.jpg', NULL),
  ('6 Underground', 2019, 'Action', 'A billionaire fakes his death to fight crime off-grid.', '/img/posters/6-underground.jpg', NULL),
  ('Red Notice', 2021, 'Action', 'An Interpol agent chases the worlds most wanted art thief.', '/img/posters/red-notice.jpg', NULL),
  ('Sweet Tooth', 2021, 'Action', 'A deer-boy hybrid journeys in a post-pandemic world.', '/img/posters/sweet-tooth.jpg', NULL),
  ('BoJack Horseman', 2014, 'Comedy', 'A washed-up sitcom horse looks for meaning.', '/img/posters/bojack.jpg', NULL),
  ('The Good Place', 2016, 'Comedy', 'A woman wakes up in the afterlife she doesnt deserve.', '/img/posters/good-place.jpg', NULL),
  ('Sex Education', 2019, 'Comedy', 'A teen runs an underground sex-advice clinic.', '/img/posters/sex-education.jpg', NULL),
  ('Never Have I Ever', 2020, 'Comedy', 'An Indian-American teen navigates high school.', '/img/posters/never-have-i-ever.jpg', NULL),
  ('Space Force', 2020, 'Comedy', 'A general builds a new branch of the US military.', '/img/posters/space-force.jpg', NULL),
  ('Grace and Frankie', 2015, 'Comedy', 'Two women bond after their husbands leave them.', '/img/posters/grace-frankie.jpg', NULL),
  ('Arcane', 2021, 'Trending', 'Sisters clash across two cities in a war of magic and tech.', '/img/posters/arcane.jpg', NULL),
  ('Maniac', 2018, 'Drama', 'Two strangers in a mysterious pharmaceutical trial.', '/img/posters/maniac.jpg', NULL)
) AS v(name, year, genre, synopsis, poster, trending_rank)
WHERE NOT EXISTS (SELECT 1 FROM titles);
